# 서버 포트 설정
server:
    port: 80

# database 연동 설정
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://database.c5j7kj2hgqne.ap-northeast-2.rds.amazonaws.com:33062/third?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: admin
        password: admin123
    thymeleaf:
        cache: false

    # spring data jpa 설정
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        open-in-view: false
        show-sql: true
        hibernate:
            ddl-auto: update # 처음엔 create로 해서 테이블 생성 후 생성 완료되면 update로 변경